[package]
name = "jack-in"
description = "an experimental sliding sync/syncv3 terminal client to jack into the matrix"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tuirealm = "1.6"
matrix-sdk = { path = "../../crates/matrix-sdk", default-features = false, features  = ["e2e-encryption", "anyhow", "native-tls", "sled", "sliding-sync"] }
matrix-sdk-common = { path = "../../crates/matrix-sdk-common" }
structopt = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
futures = { version = "0.3.1" }
tracing-subscriber = { version = "0.3" }
futures-signals = "0.3.24"
eyre = "0.6"

tui-logger = {  git = " https://github.com/gnunicorn/tui-logger", branch = "ben-update-deps" }
log = "0.4" 